### ISSUE TITLE
Be online

### ISSUE THREAD

**Issue by Deniz-seckin55** [t41372/catEncyption-GUI#1]
### **!! This is not an issue !!**
Please post something or give us a sign. I made a cat encoder/decoder too without knowing you! I hope we can be friends because we create the same stuff and I made games in unity too!

Hope you will be back @t41372 .
( I know this is not an issue but there wasn't any way to communicate )

**Comment by Deniz-seckin55** [comment]
@t41372

**Comment by t41372** [comment]
Oh... huge apology for not replying to you for 5 months. I didn't notice that there is an issue opened though. If you still want to contact me, you may send me an email at ychiu34@asu.edu ....
